name: CI

on: [push, pull_request]

jobs:
  test:
    name: Node.js v${{ matrix.nodejs }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        nodejs: [12, 14, 16, 18]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.nodejs }}

      - name: Install
        run: |
          npm install
          npm install -g c8

      - name: Compiles
        run: npm run build

      - name: Test w/ Coverage
        run: c8 --include=src npm test
        env:
          DPASTE_API_TOKEN_GIT: ${{secrets.DPASTE_API_TOKEN_GIT}}

      - name: Report
        if: matrix.nodejs >= 14
        run: |
          c8 report --reporter=text-lcov > coverage.lcov
          bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
