name: Testing & Coverage CI
permissions: read-all
on: [push, pull_request]

jobs:
  test:
    name: Node.js v${{ matrix.nodejs }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        nodejs: [18, 20]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.nodejs }}

      - name: Install dependencies
        run: npm install

      - name: Compile source code
        run: npm run build

      - name: Test w/ Coverage
        run: npm test
        env:
          DPASTE_API_TOKEN_GIT: ${{secrets.DPASTE_API_TOKEN_GIT}}

      - name: Report
        if: matrix.nodejs >= 18
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
